@LearnOdataList_HostAddress = http://localhost:5090

GET {{LearnOdataList_HostAddress}}/odata/customers/
Accept: application/json

###


GET {{LearnOdataList_HostAddress}}/odata/customers?$select=name
Accept: application/json

###

GET {{LearnOdataList_HostAddress}}/odata/customers/2
Accept: application/json

###